# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Happy (Hour) Thoughts
tagline:          'The sea is a good place to think about the future.'
description:      'from <a href="https://twitter.com/mattjcline" target="_blank">@mattjcline</a>.'
baseurl:          /

author:
  name:           'Matt Cline'
  url:            https://twitter.com/mattjcline

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]


github:
  repo:           https://github.com/mattjcline
